### ISSUE TITLE
Patches have full paths to files

### ISSUE THREAD

**Issue by phase** [FountainMC/TacoFountain#1]
The patch files start with `/home/...`, which probably shouldn't be there.

**Comment by Techcable** [comment]
Yeah, I think I need to switch away from JDiff anyways so we can have more control over the patching process.
I have a in-progress port of [DiffUtils](https://github.com/Techcable/DiffUtils) to rust which I could either finish or move to cython. DiffUtils currently won't work since python is way too slow.

**Comment by PizzaCrust** [comment]
JGit?? (patching)

**Comment by jamierocks** [comment]
Try out com.cloudbees:diff4j - it's what I used for ProPatcher

**Comment by PizzaCrust** [comment]
cloudbees always have hunk errors every time i use it

**Comment by jamierocks** [comment]
I've used it for a good two years - never failed me

**Comment by PizzaCrust** [comment]
I just think using JGit as a patching solution is better, and is easier.

**Comment by phase** [comment]
But a Rust port would be pretty fast. I'd love to work on that.

**Comment by PizzaCrust** [comment]
aren't rust binaries large

**Comment by Techcable** [comment]
I'm planning to reimplement the whole TacoSpigot build system in Gradle. The current set of bash scripts isn't a good long-term solution, and I think I have enough gradle experience to take a stab at it now.
